language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 4
  - nvm use 4
  - npm install
  - npm test
  - nvm install 5
  - nvm use 5
  - nvm test

script:
  - npm run integration-test
