language: rust
rust:
  - stable

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - npm run test-full
