// Autogenerated, do not edit. All changes will be lost.

/// <reference path="../node_modules/typescript/lib/lib.es6.d.ts" />
/// <reference path="../node_modules/retyped-node-tsd-ambient/node.d.ts" />
/// <reference path="../node_modules/retyped-prettyjson-tsd-ambient/prettyjson.d.ts" />
