// Autogenerated, do not edit. All changes will be lost.

/// <reference path="../node_modules/retyped-es6-promise-tsd-ambient/es6-promise.d.ts" />
/// <reference path="../node_modules/retyped-node-tsd-ambient/node.d.ts" />